### ISSUE TITLE
Upgrade to SpringBoot 1.5.6

### ISSUE THREAD

**Issue by Slahser** [paypal/resteasy-spring-boot#76]
got NoClassDefFoundError for ServletRegistrationBean in spring boot 1.5.6
but works fine in 1.5.3 
maybe because of some dependencies of the deprecated package of ServletRegistrationBean

**Comment by fabiocarvalho777** [comment]
That probably happened due to a jar conflict in your app, because the latest starter version (at the time you used it) supported Spring Boot 1.5.3. I have just upgraded it though. It should work now with this new starter version (2.3.3-RELEASE). I am about to release it.

**Comment by fabiocarvalho777** [comment]
Hey @Slahser , just want to let you know that I have just released version 2.3.3-RELEASE of this starter, which is aligned with Spring Boot 1.5.6. It might take a few hours though for the release artifact to synchronize with Maven central repos. It should be available no later than tomorrow.

**Comment by Slahser** [comment]
Thank you so much

**Comment by fabiocarvalho777** [comment]
You're welcome!
